apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::761520025489:role/cloudnorth-jenkins-role
      username: jenkins
      groups:
        - system:masters

    - rolearn: arn:aws:iam::761520025489:role/cloudnorth-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
